version: "3"
services:
  server:
    container_name: cpsi_server
    build:
        context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: cpsi_db
    image: mysql:8.0.21
    command:  --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
